### ISSUE TITLE
decode gif incorrect with one frame's disposeMode is DISPOSAL_BACKGROUND

### ISSUE THREAD

**Issue by nanier** [soleilpqd/giflib-ios#2]
I have a problem when decode a gif when the second frame's disposeMode is DISPOSAL_BACKGROUND. It seems like the outer area of the gif is cutted. 
Since the code is " memset(contextBuffer, 0, bufferSize ); ", I think the reason is all the context is cleared. 
I tried do not clear the context, It seems ok. But I don't think it's the correct way to deal with DISPOSAL_BACKGROUND mode.
 Is there any idea to deal with the DISPOSAL_BACKGROUND mode?

**Comment by soleilpqd** [comment]
Hi,

`contextBuffer` is a block of memory to store all pixels of current frame. It's created from beginning of decoding process. Its size is image width * image height * number of bytes to store 1 image pixel (4 bytes - RGBA).
I fill each frame bitmap data into this buffer to convert the frame to `UIImage`.
This `memset(contextBuffer, 0, bufferSize);` set all memory of buffer to value 0 (draw buffer to background color - DISPOSAL_BACKGROUND) before filling the next frame bitmap. It does not change the size of `contextBuffer`.
So your frame out of area may be related to the size of image, or info about the position of the frame in the image.

Can you provide a sample image?
What version of libgif do you use? The last time I touched this project, I used 5.0.2. Maybe this project is too old :(

**Comment by nanier** [comment]
Thanks for your replay!
I didn't change the size of `contextBuffer` either. Maybe I didn't describe my problem very clearly. 
Here is my gif's information:

firstFrame         ---   `DISPOSE_DO_NOT`      ---            canvasWidth * canvasHeight
secondFrame   ---  `DISPOSE_BACKGROUND`    ---   frameWidth * frameHeight
thirdFrame       ---   `DISPOSE_BACKGROUND`    ---   frameWidth * frameHeight

Both the second frame's size  the third frame's size is smaller than  canvas size.
The problem occurs when showing the third frame. It only showed a part of the whole image. 

I kind of figure this out by doing this: Instead of clearing the total size of `contextBuffer`,  only clear part of the `contextBuffer` with the rect of the second frame. I learned from another [gifDecoder.](https://gist.github.com/devunwired/4479231)

I'm not much sure If my way is correct. And It will be very grateful If you reply again.
Here is the sample gif.[https://github.com/nanier/A-Gif-Sample](url)

```
        case DISPOSE_BACKGROUND:
        {
            BOOL isTransparent = (gcb.TransparentColor != NO_TRANSPARENT_COLOR);
            int canvasWidth = (int)(bufferSize / (4 * gifFile->SHeight));
            ColorMapObject *colorMap = gifFile->SColorMap;
            GifColorType *colorMapEntry = &colorMap->Colors[gifFile->SBackGroundColor];
            for (int i = gifFile->Image.Top; i < height; i++) {
                for (int j = col; j < width; j++) {
                    int pixIndex = i * canvasWidth + j;
                    contextBuffer[pixIndex].red = isTransparent ? 0 : colorMapEntry->Red;
                    contextBuffer[pixIndex].green = isTransparent ? 0 : colorMapEntry->Green;
                    contextBuffer[pixIndex].blue = isTransparent ? 0 : colorMapEntry->Blue;
                    contextBuffer[pixIndex].alpha = isTransparent ? 0 : 0xff;
                }
            }
        }
```

**Comment by soleilpqd** [comment]
OK, my bad. I fixed.

Following http://www.imagemagick.org/Usage/anim_basics/, it seems that the background color is useless here. So I reset the overlaid canvas to transparency.
